#!/usr/bin/env bash

NETWORK_NAME="selenium"
HUB_NAME="selenium-hub"

if [ -z "$( podman network ls | grep "${NETWORK_NAME}" )" ]; then
	echo "Creating network ${NETWORK_NAME} ..."
	podman network create ${NETWORK_NAME}
fi

podman run \
	-it \
	--rm \
	-p 4442-4444:4442-4444 \
	--net ${NETWORK_NAME} \
	--name ${HUB_NAME} \
		selenium/hub:4.4.0-20220812
